### ISSUE TITLE
Medyk - brak sprzętu we frakcjach i propozycja co do krwi

### ISSUE THREAD

**Issue by Radekj1** [Przemro/SDS-Mission-framework#6]
Indfor
AAF 2015
- Brak Defibrylatora
- Brak apteczek

Opcjonalnie na problem z ilością krwi:
- Sprawdzenie skuteczności krwi z innymi zamiennikami?
- Łatwy dostęp do większych zapasów krwi?
- Możliwość przetransportowania krwii z dawcy do rannego :P
- Dać każdej osobie po worku krwii do plecaka, lub strzelcowi kilka worków [najlżejszy ze wszystkich]?

**Comment by Przemro** [comment]
Prawdopodobnie błąd po stornie misji, w sensie użyty chyba został starszy szablon gdzie to nie było jeszcze zrobione - bo w plikach wszystko wygląda poprawnie.

Do weryfikacji przy najbliżej rozgrywce tą frakcją.
